export const UPDATE_PARAMS_EMAIL = 'UPDATE_PARAMS_EMAIL';
export const UPDATE_PARAMS_PASSWORD = 'UPDATE_PARAMS_PASSWORD';
export const UPDATE_PARAMS_FIRSTNAME = 'UPDATE_PARAMS_FIRSTNAME';
export const UPDATE_PARAMS_LASTNAME = 'UPDATE_PARAMS_LASTNAME';
export const UPDATE_PARAMS_AGE = 'UPDATE_PARAMS_AGE';